---
- name: Touch a file 
  hosts: win
  tasks:
  - name: create file
    win_file:
      path: C:\Users\Administrateur.WIN-880S38BE1DN\Documents\coucou.txt
      state: touch
  - name: create folder
    win_file: 
      path: C:\Users\Administrateur.WIN-880S38BE1DN\Documents\Exploitation
      state: directory

  