---
- name: install basic packages on debian
  hosts: localhost
  become: yes
  tasks:
    - name: install packages
      apt:
      name: "{{ item }}"
      state:  present
      - vim
      - tree
      - git



